{% set name = "xontrib-pipeliner" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 816c6afa79a640e182b41844480d772e083855c0f6e4ecc1af64a4aba3ba33ab

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - xonsh
    - six

test:
  commands:
    - xonsh -c "xontrib load pipeliner"

about:
  home: https://github.com/anki-code/xontrib-pipeliner
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Easily process the lines using pipes in xonsh.
  doc_url: https://github.com/anki-code/xontrib-pipeliner/blob/master/README.md
  dev_url: https://github.com/anki-code/xontrib-pipeliner

extra:
  recipe-maintainers:
    - scopatz
